version: "2.2"

services:
  petclinic:
    image: nabeeljb.jfrog.io/petclinic-docker-local/alak:latest
    container_name: alak
    ports:
      - 2000:8080
    depends_on:
      - mysql  
    restart: always
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
